name: Generate Website

on:
  workflow_dispatch: # 手動実行を可能にする

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を付与
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas requests openai

      - name: Set environment variables
        run: |
          echo "RAKUTEN_API_KEY=${{ secrets.RAKUTEN_API_KEY }}" >> $GITHUB_ENV
          echo "YAHOO_API_KEY=${{ secrets.YAHOO_API_KEY }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run site generator
        run: |
          python generate_site.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto-generate website and update CSV" || echo "No changes to commit"
          git push
